### ISSUE TITLE
Horizontal FOV doesn't work as expected

### ISSUE THREAD

**Issue by cihadturhan** [Unity-Technologies/com.unity.cinemachine#1022]
Cinemachine version: 2.9.7 

Hi,
I expect that when I set camera fov to `Horizontal` and set `Horizontal FOV` in cinemachine, the horizontal viewport to be same and vertical viewport should adjust itself.
However, when I resize window, it still changes according to vertical FOV.
Here is a video:

https://github.com/user-attachments/assets/ac4556c5-1a9b-4f8e-82f1-44cdfab00424

![image](https://github.com/user-attachments/assets/7bc9faec-98cc-4867-9b11-88cb15aab80c)

Expected:

<table>
<tr>
<td>
<img width="534" alt="image" src="https://github.com/user-attachments/assets/962db60d-87b0-4fbb-a36e-9a7a6252aae8">
</td>
<td>
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/6f7c18cb-c3f0-4bd7-b590-d14f6ce6e8bf">
</td>
<tr>
</table>

**Comment by glabute** [comment]
This has nothing to do with Ciemachine.  It's because you've set your game view to "Free Aspect", which takes the window aspect into account.  Change it to something else.

![image](https://github.com/user-attachments/assets/66959350-5b9c-4b7a-be47-ad4dc948d97a)
