### ISSUE TITLE
CinemachineFreeLookCam

### ISSUE THREAD

**Issue by USuperMe** [Unity-Technologies/com.unity.cinemachine#143]
![CinemachineFreeLookCam](https://user-images.githubusercontent.com/23027990/102685463-c4e7ae00-421b-11eb-80b2-6a8cbfbf1a0c.png)

Hello ,CinemachineFreeLook Custom Orbits (Top Rig,Middle Rig, BottomRig) By Bézier curve ,No Circle Path .

**Comment by glabute** [comment]
I don't understand what you are trying to say.  Can you please clarify?
