### ISSUE TITLE
Feature Request: Add OnBlendComplete / OnCameraTransitionComplete event to Cinemachine Brain

### ISSUE THREAD

**Issue by thsbrown** [Unity-Technologies/com.unity.cinemachine#17]
Currently we have no simple way to be notified when a Cinemachine camera has been fully transitioned to. I propose a OnBlendComplete / OnCameraTransition event be added to the Cinemachine brain component in order to allow developers to easily integrate game behavior when a camera is fully transitioned / blended to.

After thinking about it a bit, one decent way of integrating this behavior would be something like the following.

`OnCameraTransitionComplete(ICinemachineCamera fromCamera, ICinemachineCamera toCamera, CinemachineVirtualCameraBase managerInvokingBlend = null)`

While I admit the above could use some work, it at least covers all the information I think that should be sent along with the event. To elaborate a bit more on the last parameter, that would just be the reference of whichever manager camera the user might be using that invoked the blend. 

Below are some additional links to places on the forum where people have discussed this functionality.

- https://forum.unity.com/threads/oncameratransition-onblendcomplete-event.520056/
- https://forum.unity.com/threads/whats-the-best-way-to-contribute-to-cinemachine-vote-on-upcoming-features.710321/
- https://forum.unity.com/threads/how-can-i-tell-when-ive-reached-my-active-virtual-cam-blend-has-completed.498544/

Thanks in advance!

**Comment by Dairnon** [comment]
This would be great

**Comment by thsbrown** [comment]
Hey @Dairnon I went ahead and solved this issue in my game and figured I would just go ahead and open source the repo so you can use it to. Check it out [here](https://github.com/Breakstep-Studios/toms-cinemachine-tools).

Please excuse the lack of good documentation. I'll try and add that as soon as I can. Here's a quick look at how it works (I'm hooking in to the UnityEvents in code which is why you don't see them in editor)

![image](https://user-images.githubusercontent.com/2967721/101805001-19c25080-3ac7-11eb-88aa-3c0456d527eb.png)
