### ISSUE TITLE
Game Window Guides when Rendering to a texture

### ISSUE THREAD

**Issue by demolen** [Unity-Technologies/com.unity.cinemachine#296]
Hi,

I have realized that the cinemachine would not draw the game window guides if the camera is rendering to a texture. I have tried bypassing this by removing the check: 
` (brain.OutputCamera.activeTexture != null && CinemachineCore.Instance.BrainCount > 1)` from the following statement in CinemachineComposerEditor.cs:

```
// Don't draw the guides if rendering to texture
            CinemachineBrain brain = CinemachineCore.Instance.FindPotentialTargetBrain(vcam);
            if (brain == null || (brain.OutputCamera.activeTexture != null && CinemachineCore.Instance.BrainCount > 1))
                return;
```
                
by removing this check, I hoped that the Cinemachine would draw the guides, but it still doesn't. Am I missing something?

**Comment by glabute** [comment]
The guides are implemented as UIElements widgets on top of the Game window.  There is no simple way to get them to draw inside a texture.  You will have to implement this on your own.
