### ISSUE TITLE
CinemachineDollyCart doesn't work in Edit mode

### ISSUE THREAD

**Issue by Dem0n13** [Unity-Technologies/com.unity.cinemachine#312]
I try to use CinemachineDollyCart with CinemachineSmoothPath and it works in Play mode, but it can't show Preview in Edit mode / Timeline tab.

Is it possible to Preview cutscenes when using CinemachineDollyCart?

**Comment by glabute** [comment]
Please post questions on the Cinemachine forum: https://forum.unity.com/forums/cinemachine.136/
