### ISSUE TITLE
v2.8+ Freelook Y-Axis value can't be changed!

### ISSUE THREAD

**Issue by drg8** [Unity-Technologies/com.unity.cinemachine#352]
the current Y-axis value of freelook can't be changed manually, it automatically reverts back to default values of 
"1, 0.5, 0" depending on the rig to which the gameobject is closest at start. issue is appearing in v2.8 and above.

in v2.7.9 setting the Y-axis value defines the starting position of the rig when the game is started. in the latest version there are specific tabs for top, mid n bottom rigs, & clicking on them to set their values automatically changes the current Y-axis value & it can't be changed back & it also glitches out sometimes to how it is in v2.7.9 but didn't seem to work. tried changing it via script also doesn't work.

**Comment by glabute** [comment]
Showing the FreeLook inspector will indeed change the Y axis value so that the selected rig can be seen in the GameView.  You should be able to change it from script so long as the FreeLook inspector is not displayed.  I agree that this is not the most desirable behaviour.  Will have a think about how to make it better.

**Comment by drg8** [comment]
probably I had the freelook inspector open that changing with script didn't worked or might be due to some other reason, but didn't spend much time tinkering as I already had spend an hour wondering what's going on & why prefabs changes are not applying, so just switched back to 2021.1.28f. as of now it is very confusing, that there's a editable value but doesn't save at all. will this be fixed for next update?

**Comment by glabute** [comment]
It does save.  The problem is that the inspector modifies it without permission.  So long as you don't pop up the inspector, your saved value will be preserved.  We will try to put together a fix asap.

**Comment by drg8** [comment]
has this issue been fixed?

**Comment by glabute** [comment]
The CM3 refactor of FreeLook has solved this issue
