### ISSUE TITLE
Memory leak when calling ManualUpdate()

### ISSUE THREAD

**Issue by johanolofsson** [Unity-Technologies/com.unity.cinemachine#386]
The profiler shows 336 B allocated each frame when we call ManualUpdate on CinemachineBrain.

**Comment by glabute** [comment]
This happens specifically in the case where the PostProcessing packag is installed and there is no PostProcessing layer present on the Brain.  We have a PR in flight with the fix : https://github.com/Unity-Technologies/com.unity.cinemachine/pull/388
