### ISSUE TITLE
CinemachineVirtualCamera as Prefab Body Properties has no effect.

### ISSUE THREAD

**Issue by Shaun-Fong** [Unity-Technologies/com.unity.cinemachine#544]
Here is what I trying to do.
I try to make fps cam by using 3rd person follow. 
But when I Instantiate the CinemachineVirtualCamera prefab, Body Properties seems has no effect.
Because I find out that the first person weapon is judder , although I have completely set all parameters to 0.
So I try to change Body properties to Do nothing , then add Cinemachine3rdPersonFollow via code , set all parameters to 0, and it works!
Like this 
![image](https://user-images.githubusercontent.com/16713354/186361812-a5cdb009-723f-4183-9510-c2a89d9b87c4.png)
It is a bug I think?

**Comment by glabute** [comment]
3rdPersonFollow will only work if there is a Follow target.  You can't assign one in the prefab.  Maybe that is the problem?

Without more context it is difficult for us to tell what is happening.  3rdPersonFollow works properly in our test scenes.  If you would like to make a bug report with a repro project, you can do that with Unity->Help->ReportABug.
