### ISSUE TITLE
issues:  body of cinemachineVirtualCamera is not displayed

### ISSUE THREAD

**Issue by kimmoonwoong** [Unity-Technologies/com.unity.cinemachine#557]
![image](https://user-images.githubusercontent.com/75220547/188914071-23a1a7f7-fa64-46a3-a896-1d3702dc77f1.png)
![image](https://user-images.githubusercontent.com/75220547/188914139-08be2973-1f5d-4cea-9c37-43a07c150528.png)

The body element is showing fine on the pc and my laptop of other team members in the project, but not on my desktop.

**Comment by glabute** [comment]
Try upgrading to more recent CM version
