### ISSUE TITLE
Need On Camera Live End Event 

### ISSUE THREAD

**Issue by ChildWang** [Unity-Technologies/com.unity.cinemachine#660]
This event fires when a Virtual Camera goes live. If a blend is involved, then the event fires on the last frame of the blend.

**Comment by glabute** [comment]
What is the use-case for this feature?

**Comment by ChildWang** [comment]
Camera switch transition complete execution operation，I'm sure many people need this feature.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Unity-Technologies/com.unity.cinemachine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 凌晨0:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Unity-Technologies/com.unity.cinemachine] Need On Camera Live End Event  (Issue #660)





 
What is the use-case for this feature?

**Comment by glabute** [comment]
You can do it by polling brain.ActiveBlend.  When is is null, the transition has completed.
