### ISSUE TITLE
"AddCustomBlendable" changes behavior if more than 4 custom blendables present, breaking sync of m_Custom_Overflow and NumCustomBlendables

### ISSUE THREAD

**Issue by lgarczyn** [Unity-Technologies/com.unity.cinemachine#940]
Here is the method AddCustomBlendable

```
        public void AddCustomBlendable(CustomBlendable b)
        {
            // Attempt to merge common blendables to avoid growth
            int index = FindCustomBlendable(b.m_Custom);
            if (index >= 0)
                b.m_Weight += GetCustomBlendable(index).m_Weight;
            else
            {
                index = NumCustomBlendables;
                NumCustomBlendables = index + 1;
            }
            switch (index)
            {
                case 0: mCustom0 = b; break;
                case 1: mCustom1 = b; break;
                case 2: mCustom2 = b; break;
                case 3: mCustom3 = b; break;
                default: 
                {
                    if (m_CustomOverflow == null)
                        m_CustomOverflow = new List<CustomBlendable>();
                    m_CustomOverflow.Add(b);
                    break;
                }
            }
         }
```

It starts by trying to find if the Blendable being added already exists inside the `mCustomN` properties or `m_CustomOverflow` list.

Let's assume it did find a previous inserted blendable equal to `b`.

If this happens, the method sets `index` to point to the previous value, and adds the previous weight to `b`.

If `index` is < 4, then `b` overrides the previous value, and everything is fine

But if index happens to already fall into m_CustomOverflow, the previous value is NOT overriden. Instead, it is added at a completely different index, namely m_CustomOverflow.Length

Since NumCustomBlendables is not updated, the value is mostly ignored. However the list is now out of sync with the counter.

**Comment by glabute** [comment]
I do believe you are right.  Thank you for raising the issue.
